language: csharp
solution: Duplicati.sln
install:
  - nuget restore Duplicati.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Duplicati.sln
  - mkdir ~/testdata
  - mkdir ~/testdata/data
  - mkdir ~/testdata/DSMCBE
  - svn checkout -r 50 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r50
  - svn checkout -r 100 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r100
  - svn checkout -r 150 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r150
  - svn checkout -r 200 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r200
  - svn checkout -r 250 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r250
  - svn checkout -r 251 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r251
  - svn checkout -r 252 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r252
  - svn checkout -r 253 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r253
  - svn checkout -r 254 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r254
  - svn checkout -r 255 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r255
  - svn checkout -r 256 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r256
  - svn checkout -r 257 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r257
  - svn checkout -r 258 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r258
  - svn checkout -r 259 http://dsmcbe.googlecode.com/svn/trunk/ ~/testdata/DSMCBE/r259
  - wget "https://s3.amazonaws.com/duplicati-test-file-hosting/data.zip"
  - unzip data.zip ~/testdata/
  - ls -la ~/testdata
  - ls -la ~/testdata/data
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Duplicati/UnitTest/bin/Release/Duplicati.UnitTest.dll